apiVersion: v1
kind: Service
metadata:
  name: threat-detector
spec:
  type: {{ .Values.service.type }}
  selector:
    app: threat-detector
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
