replicaCount: 1

image:
  repository: your-dockerhub/threat-detector
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

env:
  ALERT_WEBHOOK_URL: "https://your-alert-endpoint.com/webhook"
