apiVersion: apps/v1
kind: Deployment
metadata:
  name: threat-detector
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: threat-detector
  template:
    metadata:
      labels:
        app: threat-detector
    spec:
      containers:
        - name: threat-detector
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 5000
          env:
            - name: ALERT_WEBHOOK_URL
              value: "{{ .Values.env.ALERT_WEBHOOK_URL }}"
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
